// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

/** Add your docs here. */
public class CommandConstants {
    public static final double kSourceAlignmentTolerance = 2.5;
    public static final double kRotateP = 0.005;
    public static final double kXTranslateP = 0.5;
    public static final double kYTranslateP = 0.25;
}
